version: 0.2

phases:
  install:
    commands:
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - cd python-modules && make -j 7 test-tox
      - mkdir -p serverless-functions/build/python/lib/python3.6/site-packages
      - bash deploy.sh
