version: "3"
services:
  dynalite:
    build:
      context: dockerfiles/
      dockerfile: Dynalite
    ports:
      - "4567:4567"
    volumes:
      - dynalite-data-volume:/srv/leveldb
    command: dynalite --path /srv/leveldb/db

  kinesalite:
    build:
      context: dockerfiles/
      dockerfile: Kinesalite
    ports:
      - "4568:4567"
    volumes:
      - kinesalite-data-volume:/srv/leveldb
    command: kinesalite --path /srv/leveldb/db

volumes:
  dynalite-data-volume:
  kinesalite-data-volume:
