---
version: '3.7'
services:
  tester:
    platform: linux/amd64
    build:
      context: ci/
      dockerfile: Dockerfile
    environment:
      AWS_DEFAULT_REGION: us-west-2
    volumes:
      - ./:/var/task
      - ~/.aws:/root/.aws
    networks:
      - default
