from decouple import config


ARN_MASTER_KEY = config('CIS_ARN_MASTER_KEY')
DYNAMODB_TABLE = config('CIS_DYNAMODB_TABLE')
KINESIS_STREAM_ARN = config('CIS_KINESIS_STREAM_ARN')
LAMBDA_VALIDATOR_ARN = config('CIS_LAMBDA_VALIDATOR_ARN')
