AWSTemplateFormatVersion: "2010-09-09"
Description: "Mozilla Change Integration Service Stack"
Resources:
  ### This is the stream of data flowing in from KPLs like Mozillians
  CISInputStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      ShardCount: 1
      Tags:
      - Key: Project
        Value: ChangeIntegration
      - Key: Type
        Value: Input
  ### DynamoDB Table of all users
  IdentityVaultUsers:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
      -
        AttributeName: "UserId"
        AttributeType: "S"
      KeySchema:
      -
        AttributeName: "UserId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  ### Groups table populated by loopback stream driver for fast search of group members
  IdentityVaultGroups:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
      -
        AttributeName: "GroupId"
        AttributeType: "S"
      KeySchema:
      -
        AttributeName: "GroupId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      StreamSpecification:
        StreamViewType: KEYS_ONLY
