AWSTemplateFormatVersion: 2010-09-09
Description: Create a managed policy to bind to roles that allows secret access for cis_development.
Resources:
  SecretAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows retrieval of secrets in the cis_development namespace.
      Path: '/'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ssm:GetParameterHistory"
              - "ssm:GetParametersByPath"
              - "ssm:GetParameters"
              - "ssm:GetParameter"
            Resource:
              - arn:aws:ssm:*:*:parameter/iam/cis/development/*
          - Effect: Allow
            Action:
              - "kms:Decrypt"
            Resource:
              - arn:aws:kms:us-west-2:320464205386:key/ef00015d-739b-456d-a92f-482712af4f32
      ManagedPolicyName: 'cis-development-secret-retrieval'
